### ISSUE TITLE
Double Prefix display (Townychat)

### ISSUE THREAD

**Issue by Sprungente** [LlmDl/Towny#2539]
Hello everybody

I want do use Towny in a servernetwork, but only on the Townyserver will the prefix display double. Nothing will help to fix that, so I think its a mistake from the Townychatplugin. I use Bungeeperms as Permissionssystem.

### What steps will reproduce the problem?
1. Remove Townychat
2. Remove {permprefix}
3.

### What is the expected output?
1. The Prefix will display double like [Mod][Mod]
2. No ConsoleErrors
3.

### What is your Towny version?
0.91.1.0
Townychat: 0.47

### What is your spigot/craftbukkit version?
This server is running CraftBukkit version git-Spigot-7d78b81-50acb44 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

(optional) If this is to do with permissions, 
Saved in a MYSQL Databade

(optional) If this is to do with chat,
http://pastebin.com/tRENhERk
http://pastebin.com/UvHTWUdp

**Comment by LlmDl** [comment]
```
  channel_formats:
    # This is the format which will be used for GLOBAL chat/channels.
    # This is also the format used when you have modify_chat.enable: true, but use other plugins to handle chat.
    global: '{channelTag}{townycolor}{permprefix} {playername}{townypostfix}{permsuffix}&8:{msgcolour} {msg} {townycolor}- aus {townyformatted}'
    # TOWN channel types.
    town: '{channelTag}{townycolor}{townyprefix} {permprefix}{modplayername}{townypostfix}{permsuffix}&8:{msgcolour} {msg} {townycolor}- aus {townyformatted}'
```

In the general line you have use {playername} so there shouldn't be any double prefixes. In the town line you have both {permprefix} and {modplayername}, {modplayername} uses the bukkit Displayname that other plugins (like essentials) sometimes add to.
