### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AccioAce** [LlmDl/Towny#2811]
Hello Author,

I have quite a few questions.

1. Is the towny feature mainly meant to be for pvp servers or they can be for non-pvp servers?

2. Is there way I can edit the message for Wildnerness (PVP) and Welcome to Towny Claim Message (NO PVP) it would be great If I can.

~ Thanks

**Comment by LlmDl** [comment]
Towny servers can be PVP everywhere, PVP nowhere, or PVP in some places. Its up to you primarily to decide if you want mayors being able to control their town's pvp status. 

What part of those messsages do you want to change/edit?

**Comment by AccioAce** [comment]
Hello sorry for late reply

like these message is there way to edit it. So it doesn't say (PvP) or (NoPvP). Like the messages.

- https://gyazo.com/3e5875df6a1e56858201295f93675d84
- https://gyazo.com/d1b3769f7b8ed7c84d02cd11b09df894

**Comment by LlmDl** [comment]
In the config.yml under the Notifications section set:

```
notification:
  format: '&6 ~ %s'
  splitter: '&7 - '
  area_wilderness: '&2%s'
  area_wilderness_pvp: '%s'
  area_town: '&6%s'
  area_town_pvp: ''
  owner: '&a%s'
  no_owner: '&a%s'
  plot:
    splitter: ' '
    format: '%s'
    homeblock: '&b[Home]'
    outpostblock: '&b[Outpost]'
    forsale: '&e[For Sale: %s]'
    type: '&6[%s]'
  # If set to true MC's Title and Subtitle feature will be used when crossing into a town.
  # Could be seen as intrusive/distracting, so false by default.
  using_titles: 'false'
```

Alternatively, if you just set everything to either PVP on or off (wilderness and towns,) that PVP flag shouldn't show because the PVP status isn't changing.
